{% set name = "caniusepython3" %}
{% set version = "7.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48508255db815b03a0def81beb7e9615b4fb39e07eac7e1a9268584a0829e528

build:
  number: 0
  entry_points:
    - caniusepython3 = caniusepython3.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - backports.functools_lru_cache
    - distlib
    - futures  # [py2k]
    - packaging
    - python
    - requests

test:
  imports:
    - caniusepython3
  commands:
    - caniusepython3 --help

about:
  home: https://github.com/brettcannon/caniusepython3
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Determine what projects are blocking you from porting to Python 3
  doc_url: https://github.com/brettcannon/caniusepython3/blob/master/README.md
  dev_url: https://github.com/brettcannon/caniusepython3

extra:
  recipe-maintainers:
    - chrisburr
