travis:
  secure:
    BINSTAR_TOKEN: tm01c7YPBYEuKNzLsPZpTH6b9o7gm3qMXN8YguZ7yGBxODB076Q+TAh3nGzW6fqaNDbFW1s71yTPkQv5n9JzBi/pw7y4yxGcuh9U0cWpL4a+O//OdrYnt+4iesXuce46cvGwaFEjLysIiMn3oFvVcwLA9mPQlJc6egQYEa/lKLcki8IjOd+8wMED9vil92X2Vu3SW71X2IpfoAftKGfdWu9SiMLXU8s7arD997+392/pUc2Bm7GKeLpvOdQCKtXRyj54gz8+stWppw/Z5xz4WnPHTWpK1slpeLkL8JwSP0ddfu1EVyxZGMDu7kUYrtzfGHIIKGxy/45pifFXeHG9qDbSfoLa4mI3Ydo5gpm9wA/KDV6wH9bxLEp8616eVs7t/QDExkGNcWlVfddrfa7RHc7MaPzFoPggaqf+FrV8m0mwUScUuryv1xvmhnY1wJOdrHpritBnv1PP2B/XgxPzjf3h+lMKx7PJjjqQozefRWki85gFyHlT6GT+pZDDhvOXKTXvPIgugwf85STi/wizF+22dTdRU9/Fg4mhmo3UFC/63RR/+pUDkBoSw7veqW6vSvKkACO04DPAUMpUC4JxCrxIgn7C9mOGdrmCA4UpCFoQLgzSLQwR4+SPPsZ9Fo/rgrI3lzQpew3n8tKNZ//Y/JmeR1da79nN5tfizGdLIUE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
